name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change selon la branche utilisée

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ou autre version compatible

      - name: Install MkDocs & Theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Build Site
        run: |
          mkdocs build
          touch site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
